Script started on Fri Feb 21 15:12:49 2025
[1m[7m%[27m[1m[0m                                                                                                               [0m[27m[24m[Jbernardginnjr.@Bernards-MacBook-Pro Project 3 % [K[?2004h[7m./Bernard_Ginn_3[27m[16D[27m.[27m/[27mB[27me[27mr[27mn[27ma[27mr[27md[27m_[27mG[27mi[27mn[27mn[27m_[27m3[?2004l
Banner id: 909478671
Philosopher 1 is thinking
Philosopher 2 is thinking
Philosopher 4 is thinking
Philosopher 3 is thinking
Philosopher 0 is thinking
Philosopher 1 is hungry 
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 3 is hungry 
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 2 is hungry 
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
Philosopher 1 is hungry 
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 3 is hungry 
Philosopher 0 is hungry 
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 4 is hungry 
Philosopher 2 put down Chopstick 2
Philosopher 2 put down Chopstick 3
Philosopher 2 is thinking
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 2 is hungry 
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 0 is hungry 
Philosopher 1 is hungry 
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 4 is hungry 
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 2 put down Chopstick 2
Philosopher 2 put down Chopstick 3
Philosopher 2 is thinking
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 3 is hungry 
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 1 is hungry 
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 0 is hungry 
Philosopher 2 is hungry 
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 1 is hungry 
Philosopher 4 is hungry 
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 0 is hungry 
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 2 put down Chopstick 2
Philosopher 2 put down Chopstick 3
Philosopher 2 is thinking
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 3 is hungry 
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 2 is hungry 
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
Philosopher 4 is hungry 
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 1 is hungry 
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 2 put down Chopstick 2
Philosopher 2 put down Chopstick 3
Philosopher 2 is thinking
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 0 is hungry 
Philosopher 3 is hungry 
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 1 is hungry 
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 2 is hungry 
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
Philosopher 4 is hungry 
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 3 is hungry 
Philosopher 1 is hungry 
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 2 put down Chopstick 2
Philosopher 2 put down Chopstick 3
Philosopher 2 is thinking
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 0 is hungry 
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 2 is hungry 
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
Philosopher 1 is hungry 
Philosopher 3 is hungry 
Philosopher 4 is hungry 
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 2 put down Chopstick 2
Philosopher 2 put down Chopstick 3
Philosopher 2 is thinking
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 0 is hungry 
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 4 put down Chopstick 4
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 4 is hungry 
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 2 is hungry 
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
Philosopher 1 is hungry 
Philosopher 2 put down Chopstick 2
Philosopher 2 put down Chopstick 3
Philosopher 2 is thinking
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 3 is hungry 
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 0 is hungry 
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 2 is hungry 
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 4 is hungry 
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 3 is hungry 
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 1 is hungry 
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 4 is hungry 
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 4 is hungry 
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 0 is hungry 
Philosopher 2 put down Chopstick 2
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 2 put down Chopstick 3
Philosopher 2 is thinking
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 2 is hungry 
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
Philosopher 0 is hungry 
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 3 is hungry 
Philosopher 2 put down Chopstick 2
Philosopher 2 put down Chopstick 3
Philosopher 2 is thinking
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 1 is hungry 
Philosopher 4 is hungry 
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 2 is hungry 
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
Philosopher 0 put down Chopstick 0
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 0 is hungry 
Philosopher 3 is hungry 
Philosopher 2 put down Chopstick 2
Philosopher 2 put down Chopstick 3
Philosopher 2 is thinking
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 4 is hungry 
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 3 is hungry 
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 2 is hungry 
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 0 is hungry 
Philosopher 1 is hungry 
Philosopher 4 put down Chopstick 4
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 4 is hungry 
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 3 is hungry 
Philosopher 2 put down Chopstick 2
Philosopher 2 put down Chopstick 3
Philosopher 2 is thinking
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 2 is hungry 
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 1 is hungry 
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 4 is hungry 
Philosopher 0 is hungry 
Philosopher 3 put down Chopstick 3
Philosopher 3 put down Chopstick 4
Philosopher 3 is thinking
Philosopher 2 picked up Chopstick 3, now is eating with two chopsticks.
Philosopher 4 picked up Chopstick 4, can not eat with one chopstick.
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
Philosopher 3 is hungry 
Philosopher 2 put down Chopstick 2
Philosopher 1 picked up Chopstick 2, now is eating with two chopsticks.
Philosopher 3 picked up Chopstick 3, can not eat with one chopstick.
Philosopher 2 put down Chopstick 3
Philosopher 2 is thinking
Philosopher 2 is hungry 
Philosopher 1 put down Chopstick 1
Philosopher 1 put down Chopstick 2
Philosopher 1 is thinking
Philosopher 0 picked up Chopstick 1, now is eating with two chopsticks.
Philosopher 2 picked up Chopstick 2, can not eat with one chopstick.
Philosopher 1 is hungry 
Philosopher 0 put down Chopstick 0
Philosopher 0 put down Chopstick 1
Philosopher 0 is thinking
Philosopher 4 picked up Chopstick 0, now is eating with two chopsticks.
Philosopher 1 picked up Chopstick 1, can not eat with one chopstick.
Philosopher 4 put down Chopstick 4
Philosopher 4 put down Chopstick 0
Philosopher 4 is thinking
Philosopher 3 picked up Chopstick 4, now is eating with two chopsticks.
Philosopher 0 is hungry 
Philosopher 0 picked up Chopstick 0, can not eat with one chopstick.
^C
[1m[7m%[27m[1m[0m                                                                                                               [0m[27m[24m[Jbernardginnjr.@Bernards-MacBook-Pro Project 3 % [K[?2004h[7mexit[27m[27me[27mx[27mi[27mt[?2004l

Script done on Fri Feb 21 15:13:41 2025
